#!/bin/bash
# By graysky <graysky AT archlinux DOT us>
# Inspired by some code originally written by Colin Verot

. /etc/psd.conf

# nothing to do if there is no conf file
if [[ ! -f /etc/psd.conf ]]; then
	echo "Cannnot find /etc/psd.conf so bailing.  Reinstall package to use profile-sync-daemon."
	exit 0
else
	. /etc/psd.conf
fi

# nothing to do if there are no users
if [[ -z "$USERS" ]]; then
	echo "Must define at least one user in /etc/psd.conf"
	exit 0
fi

BROWSERS=${BROWSERS:-"chromium google-chrome midori mozilla opera opera-next qupzilla conkeror.mozdev.org"} # all supported browsers

[[ -z "$VOLATILE" ]] && VOLATILE="/tmp"

# make it overrideable from the commandline / config
DAEMON_FILE=${DAEMON_FILE:-"/run/psd"}

set_which() {
	local user=$1
	local browser=$2
	homedir="$(getent passwd $SUDO_USER | grep $user | cut -d: -f6)"
	group="$(stat -c %G $homedir)"

	# reset global variables
	BACKUP=
	DIR=

	# skip homeless users
	if [[ -z $homedir ]]; then
		return
	fi

	case "$browser" in
		chromium|google-chrome|midori)
			BACKUP="$homedir/.config/$browser-backup"
			DIR="$homedir/.config/$browser"
			;;
		mozilla|opera|opera-next|qupzilla|conkeror.mozdev.org)
			BACKUP="$homedir/.$browser-backup"
			DIR="$homedir/.$browser"
			;;
		*)
			# skip invalid browser entries
			return
	esac
}

sync() {
	# used to check if psd is active
	touch "$DAEMON_FILE"

	# sync profiles to tmpfs and back again
	local browser user
	for user in $USERS; do
		for browser in $BROWSERS; do
			set_which "$user" "$browser"

			# make tmpfs container
			if [[ -d $DIR ]]; then
				[[ -r "$VOLATILE/$user-$browser" ]] || install -dm755 --owner=$user --group=$group "$VOLATILE/$user-$browser"

				# backup target and link to tmpfs container
				if [[ $(readlink "$DIR") != "$VOLATILE/$user-$browser" ]]; then
					mv "$DIR" "$BACKUP"
					ln -s "$VOLATILE/$user-$browser" "$DIR"
					chown -h $user:$group "$DIR"
				fi

				# sync the tmpfs targets to the disc
				if [[ -e $DIR/.flagged ]]; then
					rsync -aog --delete --exclude .flagged "$DIR/" "$BACKUP/"
				else
					rsync -aog "$BACKUP/" "$DIR/"
					touch "$DIR/.flagged"
				fi
			fi
		done
	done
}

debug() {
	echo "::DEBUG MODE::"
	echo
	local browser user
	for user in $USERS; do
		for browser in $BROWSERS; do
			set_which "$user" "$browser"
			echo user: $user
			echo group: $group
			echo homedir: $homedir
			echo browser: $browser
			echo
		done
	done
}

check() {
	# crash recovery
	local browser user
	for user in $USERS; do
		for browser in $BROWSERS; do
			set_which "$user" "$browser"
			[[ -h $DIR ]] && unlink "$DIR"
			[[ -d $BACKUP ]] && mv "$BACKUP" "$DIR"
		done
	done
}

unsync() {
	# remove daemon state indicator file
	rm -f "$DAEMON_FILE"

	# restore virgin state of profiles on physical discs
	local browser user
	for user in $USERS; do
		for browser in $BROWSERS; do
			set_which "$user" "$browser"
			# check if user has browser profile
			if [[ -h "$DIR" ]]; then
				unlink "$DIR"
				# this assumes that the backup is always updated so be sure to invoke a sync
				# before an unsync
				#
				# restore original dirtree
				[[ -d "$BACKUP" ]] && mv "$BACKUP" "$DIR"
				[[ -d "$VOLATILE/$user-$browser" ]] && rm -rf "$VOLATILE/$user-$browser"
			fi
		done
	done
}

case "$1" in
	debug)
		debug
		;;
	sync)
		[[ ! -f $DAEMON_FILE ]] && check
		sync
		;;
	resync)
		[[ -f $DAEMON_FILE ]] && sync
		;;
	unsync)
		# make sure the daemon is running
		[[ -f $DAEMON_FILE ]] && sync && unsync
		;;
	*) 
		echo -en "\E[31musage: "
		tput sgr0 # reset colors to normal
		echo "$0 {sync|unsync|debug}"
		echo
		echo "sync) force a manual sync."
		echo "unsync) force a manual unsync."
		echo "debug) parge config file to make sure vars are correctly defined."
		;;
esac
exit 0
