#!/bin/bash
declare -r $@

OLFS_NAME[22]=overlayfs
OLFS_NAME[23]=overlay

## TODO - pass error codes back to psd so it can break if the mount command fails
case "$ACTION" in
	mountup)
			mount -o nosuid,nodev,noexec -t ${OLFS_NAME[$OLFSVER]} overlaid -olowerdir="$BACKUP",upperdir="$TMPRW",workdir="$TMPWK" "$TMP"
		;;
	mountdown)
			umount -l "$TMP"
		;;
	*)
		echo "Do not call this script directly; psd will do so for you. Thank you, come again."
		exit 0
		;;
esac
