#!/bin/sh
set -e

if [ $(grep -c -i debian /etc/issue) = 1 ]; then
	# debian does not mount /tmp to tmpfs by default so use /dev/shm
	sed -i 's/#VOLATILE="\/tmp"/VOLATILE="\/dev\/shm"/' /etc/psd.conf
fi

if [ $(grep -c -i ubuntu /etc/issue) = 1 ]; then
	# ubuntu does not mount /tmp to tmpfs by default so use /run/shm
	sed -i 's/#VOLATILE="\/tmp"/VOLATILE="\/run\/shm"/' /etc/psd.conf
fi

echo '--------------------------------------------------------------------------'
echo '  Define which users will make use of the sync in /etc/psd.conf'
echo '  Read the manpage before use or see the wiki page'
echo '  https://wiki.archlinux.org/index.php/Profile-sync-daemon'
echo
echo '  ALWAYS backup your profiles data before using utils like psd!'
echo '--------------------------------------------------------------------------'
