#!/bin/sh

set -e

case "$1" in
	install|upgrade)

		# version 6 is a user daemon so clear out old system level files

		RUNNING=$(systemctl is-active psd)
		if [ "$RUNNING" = "active" ]; then
			systemctl stop psd &>/dev/null
		fi

		if [ -h /etc/systemd/system/multi-user.target.wants/psd.service ]; then
			rm -f /etc/systemd/system/multi-user.target.wants/psd.service
		fi

		if [ -f /etc/psd.conf ]; then
			mv /etc/psd.conf /etc/psd.conf.old
		fi
		;;

	abort-upgrade)
		;;

	*)
		echo "preinst called with unknown argument \`$1'" >&2
		exit 0
		;;
esac

exit 0
