#!/bin/sh
set -e
# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
	remove|deconfigure)
		systemctl status psd &>/dev/null
		if [[ $? -eq 0 ]]; then
			systemctl stop psd &>/dev/null
		else
			service psd stop
		fi
		;;
	upgrade|failed-upgrade)
		/bin/true
		# Do nothing
		;;
	*)
		echo "prerm called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

exit 0
