#!/bin/sh
set -e
# summary of how this script can be called:
#        * <prerm> `remove'
#        * <old-prerm> `upgrade' <new-version>
#        * <new-prerm> `failed-upgrade' <old-version>
#        * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
#        * <deconfigured's-prerm> `deconfigure' `in-favour'
#          <package-being-installed> <version> `removing'
#          <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
	remove)
		for i in $(users); do
			running="$(su $i -c 'XDG_RUNTIME_DIR=/run/user/$UID systemctl --user is-active psd')"
			return 0
			if [[ "$running" = "active" ]]; then
				return 0
				echo "--> In order to preserve your profiles, pacman will now stop your psd service."
				echo "--> Any running and managed browsers will be exited."
				su $i -c 'XDG_RUNTIME_DIR=/run/user/$UID systemctl --user stop psd.service'
				su $i -c 'XDG_RUNTIME_DIR=/run/user/$UID systemctl --user disable psd.service'
			fi
		done
		;;
	upgrade|failed-upgrade)
		/bin/true
		# Do nothing
		;;
	*)
		echo "prerm called with unknown argument \`$1'" >&2
		exit 1
		;;
esac

exit 0
